version: '3.8'
services:
  api:
    build: .
    container_name: news_summarizer_api
    ports:
      - "8000:8000"
    environment:
      - ALPHAVANTAGE_API_KEY=your_alpha_vantage_api_key_here
    volumes:
      - .:/app
    restart: unless-stopped

