
# Hardcoded example tickers and descriptions
TICKERS_DB = [
    {"symbol": "AAPL",
     "description": "Apple Inc. designs, manufactures, and markets consumer electronics, software, and services."},
    {"symbol": "GOOGL",
     "description": "Alphabet Inc. is a multinational conglomerate specializing in internet-related services and products."},
    {"symbol": "MSFT",
     "description": "Microsoft Corporation develops, licenses, and supports a wide range of software products and services."},
    {"symbol": "AMZN",
     "description": "Amazon.com, Inc. is a global e‑commerce and cloud computing giant, also involved in digital streaming and AI."},
    {"symbol": "JPM",
     "description": "JPMorgan Chase & Co. provides financial services including investment banking, asset management, and consumer banking."},
    {"symbol": "XOM",
     "description": "Exxon Mobil Corporation explores for, produces, and distributes crude oil, natural gas, and petroleum products."},
    {"symbol": "PFE",
     "description": "Pfizer Inc. discovers, develops, and manufactures healthcare products, including vaccines and specialty medicines."},
    {"symbol": "TSLA",
     "description": "Tesla, Inc. designs, manufactures, and sells electric vehicles, energy storage systems, and solar products."},
    {"symbol": "KO",
     "description": "The Coca‑Cola Company produces, markets, and sells nonalcoholic beverage concentrates and syrups worldwide."},
    {"symbol": "BA",
     "description": "The Boeing Company designs, manufactures, and services commercial jetliners, defense, space, and security systems."},
    {"symbol": "NFLX",
     "description": "Netflix, Inc. provides subscription streaming entertainment services and produces original films and series."},
    {"symbol": "NVDA",
     "description": "NVIDIA Corporation designs graphics processing units (GPUs) and AI computing technology for gaming, professional visualization, and data centers."},
    {"symbol": "DIS",
     "description": "The Walt Disney Company operates media networks, parks and resorts, studio entertainment, and direct‑to‑consumer streaming services."},
]
